# __Introduction to NumPy__

## __Agenda__

In this lesson, we will cover the following concepts with the help of examples:

- Fundamentals of NumPy
  * Advantages of NumPy
  * NumPy: Installation and Import
- NumPy: Array Object
  * Creating NumPy Arrays

## __1. Fundamentals of NumPy__

NumPy (Numerical Python) is a free and open-source library that is mostly used for mathematical operations in scientific and engineering applications.

- It is a Python library used for working with arrays.
- It consists of a multidimensional array of objects and a collection of functions for manipulating them.
- It conducts mathematical and logical operations on arrays.

**Note:** The array object in NumPy is called ndarray.

### __1.1  Advantages of NumPy__
- It provides an array object that is faster than traditional Python lists.
- It provides supporting functions.
- Arrays are frequently used in data science.
- NumPy arrays are stored in one continuous place in memory, unlike lists.

### __1.2 NumPy: Installation and Import__
- `C:\Users\Your Name>pip install numpy` command is used to install NumPy.
- NumPy is imported under the name np like `import numpy as np`.

## __2. NumPy: Array Object__
A NumPy ndarray object can be created by using the array() function.

In [1]:
# Example:
import numpy as np
arr = np.array ([10,20,30,40,50])
print (arr)
print (type(arr))

[10 20 30 40 50]
<class 'numpy.ndarray'>


### __2.1 Creating NumPy Arrays__
- Create multiple dimensional arrays, such as 0D, 1D, 2D and 3D

In [2]:
# Create a 0D Array
arr0 = np.array(24)
print ('0D array is', arr0)
# Create a 1D Array
arr1 = np.array([1,2,3,4])
print ('1D array is', arr1)
# Create a 2D Array
arr2 = np.array([[1,1,1],[1,2,1]])
print ('2D array is', arr2)
# Create a 3D Array
arr3 = np.array([[[1,1,1],[2,2,2]],[[3,3,3],[4,4,4]]])
print ('3D array is', arr3)

0D array is 24
1D array is [1 2 3 4]
2D array is [[1 1 1]
 [1 2 1]]
3D array is [[[1 1 1]
  [2 2 2]]

 [[3 3 3]
  [4 4 4]]]


**Observations:**
- 1D arrays are unidimensional and have 0D arrays as its elements.
- 2D arrays have 1D arrays as their elements.
- 3D arrays have 2D arrays as their elements.

## __Assisted Practice__

### __Problem Statement:__

Create the following NumPy arrays and print them using appropriate code:

- A 0D array (scalar)

- A 1D array with elements [1, 2, 3, 4]

- A 2D array with elements [[1, 1, 1], [1, 2, 1]]

- A 3D array with elements [[[1, 1, 1], [2, 2, 2]], [[3, 3, 3], [4, 4, 4]]]